name: Deploy API

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runner (keep this as is)

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user  # Remote EC2 user for Amazon Linux
        key: ${{ secrets.AWS_SECRET }}
        script: |
          cd /home/ec2-user/
          git pull origin main
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi
          sudo systemctl restart nginx