name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Runs the workflow only on PRs to the main branch
  push:
    branches:
      - main  #
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fetch repo code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: pytest  # Execute tests

      - name: Check test results
        if: failure()
        run: echo "❌ Tests failed. Fix errors before merging."

      - name: Success message
        if: success()
        run: echo "✅ All tests passed! Ready to merge."
