name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Runs when a pull request is made to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out your repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Change this if you're using a different Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this file exists and lists all dependencies

      - name: Run Tests
        run: pytest  # Runs your test cases using pytest
